Wine.create(name:'The Wine1', year:1990, winery:"wine", country: 'us', varietal: 'merlot')
Wine.create(name:'The Wine2', year:1992, winery:"wine", country: 'us', varietal: 'merlot')
Wine.create(name:'The Wine3', year:1993, winery:"wine", country: 'us', varietal: 'merlot')
Wine.create(name:'The Wine4', year:1994, winery:"wine", country: 'us', varietal: 'merlot')
Wine.create(name:'The Wine5', year:1995, winery:"wine", country: 'us', varietal: 'merlot')
Wine.create(name:'The Wine6', year:1998, winery:"wine", country: 'us', varietal: 'merlot')
